// generated by build/tools.js
const _ = () => import("../nnt/sites/Index.vue")
const manage = () => import("./manage")
const sample = () => import("./sample")
const test = () => import("./test")

export default {
  routes: [
    {
      path: '/',
      component: _,
      name: '_site_'
    },
    {
      path: '/:site',
      component: _,
      name: '_site__'
    },
    {
      path: '*',
      component: _,
      name: '_any_'
    }
  ],
  sites: {
    manage: manage,
    sample: sample,
    test: test,
    default: manage
  }
}