// generated by build/tools.js
const _components_manage = () => import("../components/manage/Manage.vue")
const _components_manage_base_base = () => import("../components/manage/base/Base.vue")
const _components_manage_chart = () => import("../components/manage/chart/Chart.vue")
const _components_manage_chart_sample = () => import("../components/manage/chart/sample/Sample.vue")
const _components_manage_droplist = () => import("../components/manage/droplist/Droplist.vue")
const _components_manage_droplist_sample = () => import("../components/manage/droplist/sample/Sample.vue")
const _components_manage_main = () => import("../components/manage/Main.vue")
const _components_manage_maincontainer = () => import("../components/manage/MainContainer.vue")
const _components_manage_table = () => import("../components/manage/table/Table.vue")
const _components_manage_table_sample = () => import("../components/manage/table/sample/Sample.vue")
const _components_sample_audiorecorder = () => import("../components/sample/AudioRecorder.vue")
const _components_sample_echo = () => import("../components/sample/Echo.vue")
const _components_sample_helloworld = () => import("../components/sample/HelloWorld.vue")
const _components_sample_sample = () => import("../components/sample/Sample.vue")
const _components_test_test = () => import("../components/test/Test.vue")


export default {
  routes: [
    {
      path: 'components/manage',
      component: _components_manage,
      name: 'components/manage',
      label: 'Manage',
      module: true,
      priority: 9999
    },
    {
      path: 'components/manage/manage',
      component: _components_manage,
      name: 'components/manage/def',
      label: 'Manage',
      module: true,
      priority: 9999
    },
    {
      path: 'components/manage/base/base/base',
      component: _components_manage_base_base,
      name: 'components/manage/base/base',
      label: 'Base'
    },
    {
      path: 'components/manage/chart/chart',
      component: _components_manage_chart,
      name: 'components/manage/chart',
      label: '图表',
      module: true,
      priority: 2
    },
    {
      path: 'components/manage/chart/sample/sample',
      component: _components_manage_chart_sample,
      name: 'components/manage/chart/sample',
      label: '简单'
    },
    {
      path: 'components/manage/droplist/droplist',
      component: _components_manage_droplist,
      name: 'components/manage/droplist',
      label: '下拉列表',
      module: true,
      priority: 3
    },
    {
      path: 'components/manage/droplist/sample/sample',
      component: _components_manage_droplist_sample,
      name: 'components/manage/droplist/sample',
      label: '简单'
    },
    {
      path: 'components/manage/manage/main',
      component: _components_manage_main,
      name: 'components/manage/main',
      label: 'Main'
    },
    {
      path: 'components/manage/manage/maincontainer',
      component: _components_manage_maincontainer,
      name: 'components/manage/maincontainer',
      label: 'MainContainer'
    },
    {
      path: 'components/manage/table/table',
      component: _components_manage_table,
      name: 'components/manage/table',
      label: '表格',
      module: true,
      priority: 1
    },
    {
      path: 'components/manage/table/sample/sample',
      component: _components_manage_table_sample,
      name: 'components/manage/table/sample',
      label: '简单'
    },
    {
      path: 'components/sample/sample/audiorecorder',
      component: _components_sample_audiorecorder,
      name: 'components/sample/audiorecorder',
      label: 'AudioRecorder'
    },
    {
      path: 'components/sample/sample/echo',
      component: _components_sample_echo,
      name: 'components/sample/echo',
      label: 'Echo'
    },
    {
      path: 'components/sample/sample/helloworld',
      component: _components_sample_helloworld,
      name: 'components/sample/helloworld',
      label: 'HelloWorld'
    },
    {
      path: 'components/sample/sample/sample',
      component: _components_sample_sample,
      name: 'components/sample/sample',
      label: 'Sample'
    },
    {
      path: 'components/test/test/test',
      component: _components_test_test,
      name: 'components/test/test',
      label: 'Test'
    }
]
}