// generated by build/tools.js
const _manage_chart_chart = () => import("../sites/manage/chart/Chart.vue")
const _manage_chart = () => import("../sites/manage/chart/Chart.vue")
const _manage_droplist = () => import("../sites/manage/droplist/Droplist.vue")
const _manage_droplist_droplist = () => import("../sites/manage/droplist/Droplist.vue")
const _manage_main = () => import("../sites/manage/Main.vue")
const _manage_maincontainer = () => import("../sites/manage/MainContainer.vue")
const _manage = () => import("../sites/manage/Manage.vue")
const _manage_manage = () => import("../sites/manage/Manage.vue")
const _manage_chart_sample_sample = () => import("../sites/manage/chart/sample/Sample.vue")
const _manage_droplist_sample_sample = () => import("../sites/manage/droplist/sample/Sample.vue")
const _manage_chart_sample = () => import("../sites/manage/chart/sample/Sample.vue")
const _manage_droplist_sample = () => import("../sites/manage/droplist/sample/Sample.vue")
const _manage_table_sample = () => import("../sites/manage/table/sample/Sample.vue")
const _manage_table_sample_sample = () => import("../sites/manage/table/sample/Sample.vue")
const _manage_table = () => import("../sites/manage/table/Table.vue")
const _manage_table_table = () => import("../sites/manage/table/Table.vue")


export default {
  routes: [
    {
      path: '/chart/chart',
      component: _manage_chart_chart,
      name: 'manage.chart.chart',
      label: 'Chart'
    },
    {
      path: '/chart',
      component: _manage_chart,
      name: 'manage.chart',
      label: '图表',
      module: true,
      priority: 2
    },
    {
      path: '/droplist',
      component: _manage_droplist,
      name: 'manage.droplist',
      label: '下拉列表',
      module: true,
      priority: 3
    },
    {
      path: '/droplist/droplist',
      component: _manage_droplist_droplist,
      name: 'manage.droplist.droplist',
      label: 'Droplist'
    },
    {
      path: '/main',
      component: _manage_main,
      name: 'manage.main',
      label: 'Main'
    },
    {
      path: '/maincontainer',
      component: _manage_maincontainer,
      name: 'manage.maincontainer',
      label: 'MainContainer'
    },
    {
      path: '/',
      component: _manage,
      name: 'manage',
      label: 'Manage',
      module: true,
      priority: 9999
    },
    {
      path: '/manage',
      component: _manage_manage,
      name: 'manage.manage',
      label: 'Manage'
    },
    {
      path: '/chart/sample/sample',
      component: _manage_chart_sample_sample,
      name: 'manage.chart.sample.sample',
      label: 'Sample'
    },
    {
      path: '/droplist/sample/sample',
      component: _manage_droplist_sample_sample,
      name: 'manage.droplist.sample.sample',
      label: 'Sample'
    },
    {
      path: '/chart/sample',
      component: _manage_chart_sample,
      name: 'manage.chart.sample',
      label: '简单',
      module: true,
      priority: 0
    },
    {
      path: '/droplist/sample',
      component: _manage_droplist_sample,
      name: 'manage.droplist.sample',
      label: '简单',
      module: true,
      priority: 0
    },
    {
      path: '/table/sample',
      component: _manage_table_sample,
      name: 'manage.table.sample',
      label: '简单',
      module: true,
      priority: 0
    },
    {
      path: '/table/sample/sample',
      component: _manage_table_sample_sample,
      name: 'manage.table.sample.sample',
      label: 'Sample'
    },
    {
      path: '/table',
      component: _manage_table,
      name: 'manage.table',
      label: '表格',
      module: true,
      priority: 1
    },
    {
      path: '/table/table',
      component: _manage_table_table,
      name: 'manage.table.table',
      label: 'Table'
    }
]
}