// generated by build/tools.js
const _sample_audiorecorder = () => import("../sites/sample/AudioRecorder.vue")
const _sample_echo = () => import("../sites/sample/Echo.vue")
const _sample_helloworld = () => import("../sites/sample/HelloWorld.vue")
const _sample = () => import("../sites/sample/Sample.vue")
const _sample_sample = () => import("../sites/sample/Sample.vue")


export default {
  routes: [
    {
      path: '/audiorecorder',
      component: _sample_audiorecorder,
      name: 'sample.audiorecorder',
      label: 'AudioRecorder'
    },
    {
      path: '/echo',
      component: _sample_echo,
      name: 'sample.echo',
      label: 'Echo'
    },
    {
      path: '/helloworld',
      component: _sample_helloworld,
      name: 'sample.helloworld',
      label: 'HelloWorld'
    },
    {
      path: '/',
      component: _sample,
      name: 'sample',
      label: 'Sample',
      module: true,
      priority: 9999
    },
    {
      path: '/sample',
      component: _sample_sample,
      name: 'sample.sample',
      label: 'Sample'
    }
]
}