// generated by build/tools.js
const _test = () => import("../sites/test/Test.vue")
const _test_test = () => import("../sites/test/Test.vue")


export default {
  routes: [
    {
      path: '/',
      component: _test,
      name: 'test',
      label: 'Test',
      module: true,
      priority: 9999
    },
    {
      path: '/test',
      component: _test_test,
      name: 'test.test',
      label: 'Test'
    }
]
}